version: '3'
services:
  backend:
    container_name: backend
    #ports:
    #  - "80:80"
    build:
      context: ./backend/

  frontend:
    container_name: frontend
    ports:
      - "80:80"
    build:
      context: ./frontend/
    
