name: Pipeline
on:
  push:
    branches:
    - main"
    - "dev/**"

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}


jobs:
  build:

    # The type of runner that the job will run on
    runs-on: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use. 
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint    
    # Run build of the application
    - name: Run build
      run: cd frontend/ && go build
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
        
    
    # Run testing on the code
    - name: Run testing
      run: cd frontend/ && go test

  push_image_to_dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Repo
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: build docker
      run: chmod +x scripts/build-docker.sh && scripts/build-docker.sh
    - name: push docker
      run: chmod +x scripts/push-docker.sh && scripts/push-docker.sh
  
      
