name: Pipeline
on:
  push:
    branches:
    - "main"
    - "dev/**"
jobs:
  build:

    # The type of runner that the job will run on
    runs-on: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint    
    # Run build of the application
    - name: Run build
      run: cd frontend/ && go build
    # Run testing on the code
    - name: Run testing
      run: cd frontend/ && go test
      